import {
  pgTable,
  text,
  integer,
  timestamp,
  varchar,
  pgEnum,
  primaryKey,
  boolean,
  date,
  index,
} from 'drizzle-orm/pg-core';
import { InferSelectModel, InferInsertModel } from 'drizzle-orm';

export const difficultyEnum = pgEnum('difficulty', ['easy', 'medium', 'hard']);
export const categoryEnum = pgEnum('category', ['emotion', 'everyday', 'work', 'opinion', 'social', 'precision']);

export const cards = pgTable('cards', {
  id: varchar('id', { length: 255 }).primaryKey(),
  sentence: text('sentence').notNull(),
  options: text('options').array().notNull(),
  answer: text('answer').notNull(),
  explanation: text('explanation').notNull(),
  difficulty: difficultyEnum('difficulty').notNull(),
  category: categoryEnum('category').notNull(),
});

// user_id accepts both real account ids (uuids from users.id) and
// anonymous ids (anon_*). We deliberately omit a FK so anon swipes work
// before sign-in; the auth/claim-anon endpoint rewrites anon ids to real
// user ids on first login.
//
// Composite PK on (user_id, card_id) prevents duplicate progress rows
// under concurrent writes — the answer endpoint uses ON CONFLICT DO
// NOTHING so retries are safe.
export const userProgress = pgTable(
  'user_progress',
  {
    userId: varchar('user_id', { length: 255 }).notNull(),
    cardId: varchar('card_id', { length: 255 }).notNull().references(() => cards.id),
    answeredAt: timestamp('answered_at').defaultNow().notNull(),
    // null = legacy row from before we tracked correctness.
    correct: boolean('correct'),
  },
  (t) => [primaryKey({ columns: [t.userId, t.cardId] })],
);

/**
 * Daily Challenge results — one row per (user, date). Used for streaks
 * tied to the daily, leaderboards, and "did I do it today?" checks.
 */
export const dailyResults = pgTable(
  'daily_results',
  {
    userId: varchar('user_id', { length: 255 }).notNull(),
    date: date('date').notNull(),
    correct: integer('correct').notNull(),
    total: integer('total').notNull(),
    completedAt: timestamp('completed_at').defaultNow().notNull(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.date] })],
);

/**
 * Append-only behavioural event log powering the admin dashboard.
 *
 * Why a separate table instead of more columns on `user_progress`:
 * that table is keyed (user_id, card_id) and written with ON CONFLICT
 * DO NOTHING, so it only ever remembers a user's FIRST answer per card.
 * Replays in /speed, repeat sessions, and mode attribution are all
 * invisible there. This table records every occurrence.
 *
 * `id` is generated by the client so a retried flush is idempotent
 * (insert uses ON CONFLICT DO NOTHING). Like `user_progress`, `user_id`
 * deliberately has no FK so anonymous (`anon_*`) traffic is recorded
 * too — the dashboard segments logged-out vs logged-in on that prefix.
 *
 * `card_id` also skips its FK on purpose: events are historical facts
 * and must survive a card being deleted or re-seeded.
 *
 * Rows are pruned by `ANALYTICS_RETENTION_DAYS` (see routes/admin.ts),
 * which keeps the table small enough to stay inside Neon's free tier.
 */
export const analyticsEvents = pgTable(
  'analytics_events',
  {
    /** Client-generated ULID-ish string; PK so flush retries dedupe. */
    id: varchar('id', { length: 64 }).primaryKey(),
    userId: varchar('user_id', { length: 255 }).notNull(),
    /** 'session_start' | 'answer' | 'session_end' | 'complete' */
    event: varchar('event', { length: 32 }).notNull(),
    /** 'scroll' | 'focus' | 'speed' | 'review' | 'daily' | null */
    mode: varchar('mode', { length: 32 }),
    /** Sub-mode detail, e.g. the category for /focus/[category]. */
    variant: varchar('variant', { length: 64 }),
    cardId: varchar('card_id', { length: 255 }),
    correct: boolean('correct'),
    /** Time on card for `answer`, session length for `session_end`. */
    durationMs: integer('duration_ms'),
    /** True when the event was emitted by a signed-in user. */
    authed: boolean('authed').notNull().default(false),
    at: timestamp('at').defaultNow().notNull(),
  },
  (t) => [
    // Every dashboard query filters by a time window first.
    index('analytics_events_at_idx').on(t.at),
    // Per-user drilldown (the users table on the dashboard).
    index('analytics_events_user_at_idx').on(t.userId, t.at),
    // Mode breakdown over a window.
    index('analytics_events_mode_at_idx').on(t.mode, t.at),
  ],
);

// ─── Auth.js / NextAuth tables ────────────────────────────────────
// Schema matches @auth/drizzle-adapter so the frontend can read/write
// the same rows. Column names use camelCase where the adapter requires
// it (userId, emailVerified, etc.) — kept verbatim on purpose.

export const users = pgTable('users', {
  id: text('id').primaryKey(),
  name: text('name'),
  email: text('email').notNull().unique(),
  emailVerified: timestamp('emailVerified', { mode: 'date' }),
  image: text('image'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  /** 6-char base32 code for share-to-add. Generated lazily. */
  friendCode: varchar('friend_code', { length: 8 }),
});

/**
 * Symmetric friendship. We INSERT both (a,b) and (b,a) on accept so
 * "list a user's friends" is a single indexed lookup with no UNION.
 */
export const friends = pgTable(
  'friends',
  {
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    friendUserId: text('friend_user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    addedAt: timestamp('added_at').defaultNow().notNull(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.friendUserId] })],
);

export const accounts = pgTable(
  'accounts',
  {
    userId: text('userId')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    type: text('type').notNull(),
    provider: text('provider').notNull(),
    providerAccountId: text('providerAccountId').notNull(),
    refresh_token: text('refresh_token'),
    access_token: text('access_token'),
    expires_at: integer('expires_at'),
    token_type: text('token_type'),
    scope: text('scope'),
    id_token: text('id_token'),
    session_state: text('session_state'),
  },
  (account) => [primaryKey({ columns: [account.provider, account.providerAccountId] })],
);

export const sessions = pgTable('sessions', {
  sessionToken: text('sessionToken').primaryKey(),
  userId: text('userId')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),
  expires: timestamp('expires', { mode: 'date' }).notNull(),
});

export const verificationTokens = pgTable(
  'verificationToken',
  {
    identifier: text('identifier').notNull(),
    token: text('token').notNull(),
    expires: timestamp('expires', { mode: 'date' }).notNull(),
  },
  (vt) => [primaryKey({ columns: [vt.identifier, vt.token] })],
);

export type Card = InferSelectModel<typeof cards>;
export type NewCard = InferInsertModel<typeof cards>;
export type UserProgress = InferSelectModel<typeof userProgress>;
export type NewUserProgress = InferInsertModel<typeof userProgress>;
export type User = InferSelectModel<typeof users>;
export type NewUser = InferInsertModel<typeof users>;
export type AnalyticsEvent = InferSelectModel<typeof analyticsEvents>;
export type NewAnalyticsEvent = InferInsertModel<typeof analyticsEvents>;